---
- name: Install php-fpm
  apt:
    name:
      - php8.1-fpm
    state: present

- name: Copy www.conf
  template:
    src: www.conf
    dest: /etc/php/8.1/fpm/www.conf
    owner: root
    group: root
    mode: 0644
  notify: restart php8.1-fpm

- name: Enable php-fpm
  systemd:
    name: php8.1-fpm
    enabled: yes
    state: started
