#cloud-config

timezone: Asia/Tokyo

groups:
  - cloud-users

users:
  - default
  - name: oci-user
    groups: cloud-users
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILp8Q54s1D7xmWArq5pctCrvhOad38bBamwwsEUOrOph oci-user

apt:
  preserve_sources_list: true
  sources:
    docker.list:
      source: deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

runcmd:
  # Install Docker.
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  # Update iptables
  - wget https://gist.githubusercontent.com/ViaSnake/88adf1184e930a532eb6a0c326f5558d/raw/f12e17e1e23d4fb6f40c7d74393fb746008aae73/rules.v4 -O /etc/iptables/rules.v4
  - iptables-restore < /etc/iptables/rules.v4
  # Remove default user
  - userdel -r ubuntu
  - groupdel ubuntu
  # Create directory
  ## So far volumes sharing by ocfs2 does not work. Fix in the future.
  #- mkdir /mnt/shared
