#cloud-config

users:
  - name: ansible
    gecos: ansible
    plain_text_passwd: ansible
    lock_passwd: False
    groups: sudo
    shell: /bin/bash
    uid: 1500

write_files:
  - path: /etc/ssh/sshd_config
    content: |

      # Allow password authentication from internal network
      Match Address 10.210.*.*
        PasswordAuthentication yes
      Match Address 192.168.100.*
        PasswordAuthentication yes
    append: true

runcmd:
  - systemctl restart sshd
