#cloud-config

users:
  - name: ansible
    gecos: ansible
    plain_text_passwd: ansible
    lock_passwd: False
    groups: sudo
    shell: /bin/bash
    uid: 1500

runcmd:
  - echo 'Match Address 10.210.*.*\n\tPasswordAuthentication yes' >> /etc/ssh/sshd_config.d/99-allow-intarnal-password-auth.conf
  - systemctl restart sshd
