---
- name: Set locale
  locale_gen:
    name: ja_JP.UTF-8
    state: present

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Set timezone
  timezone:
    name: Asia/Tokyo
