---
- name: Set locale
  locale_gen:
    name: ja_JP.UTF-8
    state: present
  become: yes

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes

- name: Set timezone
  timezone:
    name: Asia/Tokyo
  become: yes

- name: Create groups
  include_tasks:
    file: groups.yml

- name: Create users
  include_tasks:
    file: users.yml

- name: apt update
  apt:
    update_cache: yes
  become: yes
