---
- name: Set locale
  locale_gen:
    name: ja_JP.UTF-8
    state: present

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Set timezone
  timezone:
    name: Asia/Tokyo

- name: Create infra group
  group:
    name: "infra"
    gid: 1000
    state: present

- name: Create infra user
  user:
    name: "{{ user_infra_name }}"
    uid: 1000
    password: "{{ user_infra_password | password_hash( 'sha512', user_infra_salt ) }}"
    update_password: always
    group: infra
    groups: sudo
    shell: /bin/bash
    create_home: yes
    home: /home/infra
    state: present

- name: apt update
  apt:
    update_cache: yes