---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install redis-server
  apt:
    name:
      - redis-server
    state: present
  become: yes

- name: Copy redis.conf
  template:
    src: redis.conf
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: 0644
  become: yes
  notify: restart redis-server

- name: Enable redis-server
  service:
    name: redis-server
    state: started
    enabled: yes
  become: yes
