---
- name: restart zabix-agent2
  service:
    name: zabbix-agent2
    state: restarted
    enabled: yes
  become: yes

- name: restart zabix-server
  service:
    name: zabbix-server
    state: restarted
    enabled: yes
  become: yes
