services:
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
    env_file:
      - /home/infra/secrets/cloudlared.env
