---
- name: Install Zabbix Agent
  ansible.builtin.apt:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present
  become: true

- name: Add zabbix user to docker group
  ansible.builtin.user:
    name: zabbix
    groups: docker
    append: true
  become: true

- name: Copy Zabbix Agent Configuration
  ansible.builtin.copy:
    src: ./etc/zabbix/zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart zabbix-agent

- name: Create /var/lib/zabbix directory
  ansible.builtin.file:
    path: /var/lib/zabbix
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true
  notify: restart zabbix-agent

- name: Enable Zabbix Agent
  ansible.builtin.service:
    name: zabbix-agent2
    enabled: true
    state: started
  become: true
