---
- name: Install unbound
  ansible.builtin.apt:
    name:
      - unbound
    state: absent
    update_cache: yes
  become: true

# - name: Enable unbound
#   ansible.builtin.systemd:
#     name: unbound
#     enabled: yes
#     state: started
#   become: true

# - name: Copy unbound configuration
#   ansible.builtin.copy:
#     src: ./etc/unbound/unbound.conf
#     dest: /etc/unbound/unbound.conf
#   become: true
#   notify:
#     - Restart unbound

- name: Delete unbound configuration
  ansible.builtin.file:
    path: /etc/unbound/unbound.conf
    state: absent
  become: true
