---
- name: Install sshpass
  apt:
    name:
      - sshpass
    state: present
  become: yes

- name: Install ansible
  pip:
    name:
      - ansible
    extra_args: --user
  check_mode: no
  become: true
  become_user: infra
