---
- name: Install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present
  become: true

- name: Enable docker
  systemd:
    name: docker
    enabled: true
    state: started
  become: true
