---
- name: Download Zabbix Package
  get_url:
    url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
    dest: "/tmp/{{ zabbix_package_name }}"
    checksum: "{{ zabbix_package_checksum }}"
  become: yes

- name: Install Zabbix Package
  apt:
    deb: "/tmp/{{ zabbix_package_name }}"
    update_cache: yes
  become: yes

- name: Install Zabbix Agent
  apt:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present
  become: yes

- name: Add zabbix user to docker group
  user:
    name: zabbix
    groups: docker
    append: yes
  become: yes

- name: Copy Zabbix Agent Configuration
  copy:
    src: ./etc/zabbix/zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart zabbix-agent

- name: Create /var/lib/zabbix directory
  file:
    path: /var/lib/zabbix
    state: directory
    owner: root
    group: root
    mode: 0755
  become: yes
  notify: restart zabbix-agent

- name: Enable Zabbix Agent
  systemd:
    name: zabbix-agent2
    enabled: yes
    state: started
  become: yes
