---
- name: Install Nginx
  apt:
    name:
      - nginx
    state: present
  become: yes

- name: Copy Zabbix Nginx Config
  template:
    src: zabbix.conf
    dest: /etc/nginx/conf.d/zabbix.conf
  become: yes
  notify: restart nginx

- name: Enable Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started
  become: yes
