---
- name: Download Zabbix Package
  get_url:
    url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
    dest: /tmp/zabbix-release_6.0-4+ubuntu22.04_all.deb

- name: Install Zabbix Package
  shell: dpkg -i /tmp/zabbix-release_6.0-4+ubuntu22.04_all.deb

- name: Update apt
  apt:
    update_cache: yes

- name: Install Zabbix Agent
  apt:
    name:
      - zabbix-agent
    state: present

- name: Copy Zabbix Agent Configuration
  template:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart zabbix-agent

- name: Enable Zabbix Agent
  systemd:
    name: zabbix-agent
    enabled: yes
    state: started
