---
- name: Create infra user
  user:
    name: "{{ user_infra_name }}"
    uid: 1000
    password: "{{ user_infra_password | password_hash( 'sha512', user_infra_salt ) }}"
    update_password: always
    group: infra
    groups: sudo
    shell: /bin/bash
    create_home: true
    home: /home/infra
    state: present

- name: Set authorized key
  authorized_key:
    user: "{{ user_infra_name }}"
    state: present
    key: "{{ lookup('file', './infra_id_ed25519.pub') }}"
