---
- name: Install MySQL Server
  apt:
    update_cache: yes
    name:
      - mysql-server-8.0
      - mysql-client-8.0
      - python3-pymysql
    state: present

- name: Set MySQL Root Password
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "root"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    state: present

- name: Remove anonymous users
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: ""
    state: absent

- name: Create Zabbix Database
  mysql_db:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "{{ mysql_zabbix_dbname }}"
    state: present

- name: Create Zabbix User
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "{{ mysql_zabbix_user }}"
    password: "{{ mysql_zabbix_password }}"
    host: "10.210.2.%"
    priv: "zabbix.*:ALL"
    state: present

- name: Copy mysqld.cnf
  template:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

- name: Enable MySQL Service
  service:
    name: mysql
    enabled: yes
    state: restarted
