---
- name: Git clone kitsunebi
  git:
    repo: "https://github.com/alflag-team/infra-core.git"
    dest: "/home/infra/repos/infra-core"
    version: "master"
  become: yes
  become_user: infra

- name: Create symlink to terraform
  file:
    src: "/home/infra/repos/infra-core/terraform"
    dest: "/home/infra/terraform"
    state: link
    owner: infra
    group: infra
  become: yes
  become_user: infra

- name: Create symlink to ansible
  file:
    src: "/home/infra/repos/infra-core/ansible"
    dest: "/home/infra/ansible"
    state: link
    owner: infra
    group: infra
  become: yes
  become_user: infra

- name: mkdir data directory
  file:
    path: "/home/infra/data"
    state: directory
    owner: infra
    group: infra
    mode: "0755"
  become: yes
  become_user: infra

- name: mkdir dist directory
  file:
    path: "/home/infra/dist"
    state: directory
    owner: infra
    group: infra
    mode: "0755"
  become: yes
  become_user: infra
