---
- name: Download Zabbix Package
  get_url:
    url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
    dest: "/tmp/{{ zabbix_package_name }}"
    checksum: "{{ zabbix_package_checksum }}"
  become: yes

- name: Install Zabbix Package
  apt:
    deb: "/tmp/{{ zabbix_package_name }}"
    update_cache: yes
  become: yes

- name: Install Zabbix Server
  apt:
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - fonts-ipafont-gothic
    state: present
  become: yes

- name: Copy Zabbix Server Configuration
  template:
    src: ./etc/zabbix/zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart zabbix-server

- name: Create Symbolic Link
  file:
    src: /usr/share/fonts/opentype/ipafont-gothic/ipag.ttf
    dest: /usr/share/zabbix/assets/fonts/ipag.ttf
    state: link
  become: yes
  notify: restart zabbix-server

- name: Replace ZBX_GRAPH_FONT_NAME
  lineinfile:
    path: /usr/share/zabbix/include/defines.inc.php
    regexp: "^define\\('ZBX_GRAPH_FONT_NAME',.*$"
    line: "define('ZBX_GRAPH_FONT_NAME', 'ipag');"
  become: yes
  notify: restart zabbix-server

- name: Enable Zabbix Server
  systemd:
    name: zabbix-server
    enabled: yes
    state: started
  become: yes

- name: Install Zabbix Agent
  apt:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present
  become: yes

- name: Copy Zabbix Agent Configuration
  copy:
    src: ./etc/zabbix/zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart zabbix-agent2

- name: Enable Zabbix Agent
  systemd:
    name: zabbix-agent2
    enabled: yes
    state: started
  become: yes
